import "./globals.css";
import type { Metadata } from "next";
import NavigationBar from "@/components/navbar";
import AdminNavbar from "@/components/adminNavbar";

import { Nunito } from "next/font/google";

const nunito = Nunito({ weight: ["800"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${nunito.className} dark:bg-black dark:text-neutral-300`}
            >
                <NavigationBar />
                {children}
                <AdminNavbar />
            </body>
        </html>
    );
}
